<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="model"
    nsURI="http://www.users.exa.unicen.edu.ar/~arago/srs" nsPrefix="edu.isistan.dal.srs">
  <eClassifiers xsi:type="ecore:EClass" name="Artifact" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Content" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Project" abstract="true" eSuperTypes="#//Artifact">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Documents" upperBound="-1"
        eType="#//Document"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Stakeholders" upperBound="-1"
        eType="#//Stakeholder"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Stakeholder" abstract="true" eSuperTypes="#//Artifact"/>
  <eClassifiers xsi:type="ecore:EClass" name="Document" abstract="true" eSuperTypes="#//Artifact">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Sections" upperBound="-1"
        eType="#//Section"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Section" eSuperTypes="#//Artifact">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Subsections" upperBound="-1"
        eType="#//Section" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
